[package]
name = "opentelemetry-otlp"
version = "0.1.0"
authors = ["Andreas Wiede <andreas.s.wiede@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio = "0.6"
opentelemetry = { version = "0.7.0", default-features = false, features = ["trace"], path = ".." }

[build-dependencies]
protobuf-codegen-pure = "2.16"
