[package]
name = "opentelemetry-otlp"
version = "0.1.0"
authors = ["Andreas Wiede <andreas.s.wiede@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
grpcio = "0.6"
opentelemetry = { version = "0.7.0", default-features = false, features = ["trace"], path = ".." }
protobuf = "~2"

[build-dependencies]
protoc-grpcio = "2.0"
